import 'scene_motion_recipe_models.dart';

class SceneMotionRecipeLibrary {
  const SceneMotionRecipeLibrary();

  static const List<SceneMotionRecipeDefinition> _definitions =
      <SceneMotionRecipeDefinition>[
    // Entrance
    SceneMotionRecipeDefinition(
      id: 'slideInFromLeft',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': -180, 'y': 0},
          toValue: <String, double>{'x': 0, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.85,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'cardShell', 'title', 'body'},
      aspectBias: 'horizontal',
      tasteNotes: 'Use for horizontal reveal with clean momentum.',
    ),
    SceneMotionRecipeDefinition(
      id: 'slideInFromRight',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 180, 'y': 0},
          toValue: <String, double>{'x': 0, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.85,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'cardShell', 'title', 'body'},
      aspectBias: 'horizontal',
      tasteNotes: 'Mirror pair with slideInFromLeft for balanced choreography.',
    ),
    SceneMotionRecipeDefinition(
      id: 'slideInFromTop',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': -140},
          toValue: <String, double>{'x': 0, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.8,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'title', 'group'},
      aspectBias: 'vertical',
      tasteNotes: 'Best for title and header entrances in portrait layouts.',
    ),
    SceneMotionRecipeDefinition(
      id: 'slideInFromBottom',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 140},
          toValue: <String, double>{'x': 0, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.8,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'cardShell', 'group'},
      aspectBias: 'vertical',
      tasteNotes: 'Good for CTA and lower-third components.',
    ),
    SceneMotionRecipeDefinition(
      id: 'softFadeUp',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 44},
          toValue: <String, double>{'x': 0, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'component', 'body', 'background'},
      tasteNotes: 'Quiet entrance for supporting elements.',
    ),
    SceneMotionRecipeDefinition(
      id: 'scaleIn',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 0.88,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.9,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'cardShell', 'icon'},
      tasteNotes: 'Reliable default for clean component reveal.',
    ),
    SceneMotionRecipeDefinition(
      id: 'scaleInBounce',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 0.0,
          toValue: 1.1,
          startFraction: 0.0,
          endFraction: 0.58,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.1,
          toValue: 1.0,
          startFraction: 0.58,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.5,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'icon', 'cardShell'},
      tasteNotes: 'Attention draw with controlled spring settle.',
    ),
    SceneMotionRecipeDefinition(
      id: 'popInSpring',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 0.72,
          toValue: 1.06,
          startFraction: 0.0,
          endFraction: 0.7,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.06,
          toValue: 1.0,
          startFraction: 0.7,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.65,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'cardShell', 'icon', 'title'},
      tasteNotes: 'Professional spring pop used for hero components.',
    ),
    SceneMotionRecipeDefinition(
      id: 'rotateIn',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'rotate',
          property: 'rotation',
          fromValue: -14.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.8,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'cardShell', 'icon'},
      tasteNotes: 'Adds controlled directional energy.',
    ),
    SceneMotionRecipeDefinition(
      id: 'blurIn',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'fx',
          property: 'blur',
          fromValue: 12.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.72,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'component', 'title', 'body'},
      tasteNotes: 'Text entrance with cinematic settle.',
    ),
    SceneMotionRecipeDefinition(
      id: 'stampDown',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.4,
          toValue: 0.92,
          startFraction: 0.0,
          endFraction: 0.52,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 0.92,
          toValue: 1.0,
          startFraction: 0.52,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'icon', 'button'},
      tasteNotes: 'Impactful stamp for click moments.',
    ),
    SceneMotionRecipeDefinition(
      id: 'drawOn',
      category: SceneMotionRecipeCategory.entrance,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'draw',
          property: 'reveal',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'line', 'shape'},
      tasteNotes: 'Useful for line and stroke-based elements.',
    ),
    // Exit
    SceneMotionRecipeDefinition(
      id: 'slideOutToLeft',
      category: SceneMotionRecipeCategory.exit,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 0},
          toValue: <String, double>{'x': -180, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'fade',
          property: 'opacity',
          fromValue: 1.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 0.95,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'component', 'group', 'cardShell'},
      aspectBias: 'horizontal',
      tasteNotes: 'Directional exit with strong readability.',
    ),
    SceneMotionRecipeDefinition(
      id: 'slideOutToRight',
      category: SceneMotionRecipeCategory.exit,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 0},
          toValue: <String, double>{'x': 180, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'fade',
          property: 'opacity',
          fromValue: 1.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 0.95,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'component', 'group', 'cardShell'},
      aspectBias: 'horizontal',
      tasteNotes: 'Mirror pair with slideOutToLeft.',
    ),
    SceneMotionRecipeDefinition(
      id: 'slideOutToTop',
      category: SceneMotionRecipeCategory.exit,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 0},
          toValue: <String, double>{'x': 0, 'y': -120},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'fade',
          property: 'opacity',
          fromValue: 1.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 0.95,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'component', 'group'},
      aspectBias: 'vertical',
      tasteNotes: 'Clean exit for portrait compositions.',
    ),
    SceneMotionRecipeDefinition(
      id: 'slideOutToBottom',
      category: SceneMotionRecipeCategory.exit,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 0},
          toValue: <String, double>{'x': 0, 'y': 120},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'fade',
          property: 'opacity',
          fromValue: 1.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 0.95,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'component', 'group'},
      aspectBias: 'vertical',
      tasteNotes: 'Soft downward exit for neutral scene endings.',
    ),
    SceneMotionRecipeDefinition(
      id: 'scaleOut',
      category: SceneMotionRecipeCategory.exit,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.0,
          toValue: 0.86,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'fade',
          property: 'opacity',
          fromValue: 1.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'component', 'group', 'cardShell', 'icon'},
      tasteNotes: 'Universal fallback exit for compact elements.',
    ),
    SceneMotionRecipeDefinition(
      id: 'pushBack',
      category: SceneMotionRecipeCategory.exit,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.0,
          toValue: 0.72,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'fx',
          property: 'blur',
          fromValue: 0.0,
          toValue: 8.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'fade',
          property: 'opacity',
          fromValue: 1.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'group', 'cardShell'},
      tasteNotes: 'Depth-style transition to next scene.',
    ),
    SceneMotionRecipeDefinition(
      id: 'whipPan',
      category: SceneMotionRecipeCategory.exit,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 0},
          toValue: <String, double>{'x': -420, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'fade',
          property: 'opacity',
          fromValue: 1.0,
          toValue: 0.0,
          startFraction: 0.4,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'component', 'group', 'backgroundElement'},
      tasteNotes: 'High-energy transition with motion blur-friendly velocity.',
    ),
    SceneMotionRecipeDefinition(
      id: 'fadeCollapse',
      category: SceneMotionRecipeCategory.exit,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.0,
          toValue: 0.92,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'fade',
          property: 'opacity',
          fromValue: 1.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'component', 'cardShell', 'group'},
      tasteNotes: 'Subtle de-emphasis before scene cut.',
    ),
    SceneMotionRecipeDefinition(
      id: 'maskWipeOut',
      category: SceneMotionRecipeCategory.exit,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'wipe',
          property: 'reveal',
          fromValue: 1.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'group', 'text'},
      tasteNotes: 'Mask-style exit for typography and cards.',
    ),
    // Text
    SceneMotionRecipeDefinition(
      id: 'typewriterFixedFrame',
      category: SceneMotionRecipeCategory.text,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'typewriter',
          property: 'typewriterProgress',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'linear',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.linear',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'text', 'title', 'body'},
      tasteNotes: 'Fixed-frame typewriter reveal for prompt-style text.',
      motionBlur: false,
    ),
    SceneMotionRecipeDefinition(
      id: 'wordCascadeUp',
      category: SceneMotionRecipeCategory.text,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 24},
          toValue: <String, double>{'x': 0, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.9,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'text', 'title', 'body'},
      tasteNotes: 'Readable cascade feel for labels and short lines.',
    ),
    SceneMotionRecipeDefinition(
      id: 'lineRevealMask',
      category: SceneMotionRecipeCategory.text,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'draw',
          property: 'reveal',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'text', 'body'},
      tasteNotes: 'Mask reveal for body copy and details.',
      motionBlur: false,
    ),
    SceneMotionRecipeDefinition(
      id: 'captionPop',
      category: SceneMotionRecipeCategory.text,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 0.9,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.8,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'text', 'caption', 'body'},
      tasteNotes: 'Caption-like quick emphasis.',
    ),
    SceneMotionRecipeDefinition(
      id: 'headlineBlurSettle',
      category: SceneMotionRecipeCategory.text,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'fx',
          property: 'blur',
          fromValue: 8.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': -18},
          toValue: <String, double>{'x': 0, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.9,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'title'},
      tasteNotes: 'Hero headline reveal with premium settle.',
    ),
    // Icon
    SceneMotionRecipeDefinition(
      id: 'iconPop',
      category: SceneMotionRecipeCategory.icon,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 0.5,
          toValue: 1.08,
          startFraction: 0.0,
          endFraction: 0.65,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.08,
          toValue: 1.0,
          startFraction: 0.65,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'icon', 'component'},
      tasteNotes: 'Icon-first component choreography.',
    ),
    SceneMotionRecipeDefinition(
      id: 'iconPress',
      category: SceneMotionRecipeCategory.icon,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.0,
          toValue: 0.9,
          startFraction: 0.0,
          endFraction: 0.45,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 0.9,
          toValue: 1.0,
          startFraction: 0.45,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'icon', 'button'},
      tasteNotes: 'Tap feedback for icon controls.',
      motionBlur: false,
    ),
    SceneMotionRecipeDefinition(
      id: 'iconPulse',
      category: SceneMotionRecipeCategory.icon,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.0,
          toValue: 1.08,
          startFraction: 0.0,
          endFraction: 0.5,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.08,
          toValue: 1.0,
          startFraction: 0.5,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'icon'},
      tasteNotes: 'Subtle emphasis pulse.',
    ),
    SceneMotionRecipeDefinition(
      id: 'iconOrbitMicro',
      category: SceneMotionRecipeCategory.icon,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'rotate',
          property: 'rotation',
          fromValue: -8.0,
          toValue: 8.0,
          startFraction: 0.0,
          endFraction: 0.5,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'rotate',
          property: 'rotation',
          fromValue: 8.0,
          toValue: 0.0,
          startFraction: 0.5,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'icon'},
      tasteNotes: 'Micro orbit for dynamic UI hints.',
    ),
    SceneMotionRecipeDefinition(
      id: 'plusPressToFill',
      category: SceneMotionRecipeCategory.icon,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'press',
          property: 'scale',
          fromValue: 1.0,
          toValue: 0.88,
          startFraction: 0.0,
          endFraction: 0.35,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'cover',
          property: 'scale',
          fromValue: 0.88,
          toValue: 12.0,
          startFraction: 0.35,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'button', 'icon', 'component'},
      tasteNotes: 'Used for plus button press into fullscreen transition.',
    ),
    SceneMotionRecipeDefinition(
      id: 'sendPress',
      category: SceneMotionRecipeCategory.icon,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'press',
          property: 'scale',
          fromValue: 1.0,
          toValue: 0.85,
          startFraction: 0.0,
          endFraction: 0.38,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'press',
          property: 'scale',
          fromValue: 0.85,
          toValue: 1.0,
          startFraction: 0.38,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'icon', 'button'},
      tasteNotes: 'Send action tap response.',
      motionBlur: false,
    ),
    // Card + group
    SceneMotionRecipeDefinition(
      id: 'cardSpringEntrance',
      category: SceneMotionRecipeCategory.card,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 0.82,
          toValue: 1.03,
          startFraction: 0.0,
          endFraction: 0.72,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.03,
          toValue: 1.0,
          startFraction: 0.72,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.7,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'cardShell', 'component'},
      tasteNotes: 'Default premium card entrance.',
    ),
    SceneMotionRecipeDefinition(
      id: 'cardStackCascade',
      category: SceneMotionRecipeCategory.card,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 84},
          toValue: <String, double>{'x': 0, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.85,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'cardShell', 'group'},
      tasteNotes: 'Stacked vertical cascade for card groups.',
      staggerMs: 80,
    ),
    SceneMotionRecipeDefinition(
      id: 'cardFlipSoft',
      category: SceneMotionRecipeCategory.card,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'rotate',
          property: 'rotation',
          fromValue: -10.0,
          toValue: 0.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.9,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'cardShell'},
      tasteNotes: 'Soft card flip for accent moments.',
    ),
    SceneMotionRecipeDefinition(
      id: 'cardLiftHover',
      category: SceneMotionRecipeCategory.card,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 10},
          toValue: <String, double>{'x': 0, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'cardShell'},
      tasteNotes: 'Micro lift to avoid static feel.',
    ),
    SceneMotionRecipeDefinition(
      id: 'groupBounceIn',
      category: SceneMotionRecipeCategory.group,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 0.9,
          toValue: 1.04,
          startFraction: 0.0,
          endFraction: 0.6,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.04,
          toValue: 1.0,
          startFraction: 0.6,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'group', 'component'},
      tasteNotes: 'Group-level bounce for clustered elements.',
    ),
    SceneMotionRecipeDefinition(
      id: 'cascadeSlideIn',
      category: SceneMotionRecipeCategory.group,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 68},
          toValue: <String, double>{'x': 0, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.85,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'group', 'cardShell'},
      tasteNotes: 'General-purpose staggered slide-in group behavior.',
      staggerMs: 80,
    ),
    SceneMotionRecipeDefinition(
      id: 'cascadeScaleIn',
      category: SceneMotionRecipeCategory.group,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 0.9,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.85,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'group', 'cardShell', 'icon'},
      tasteNotes: 'Balanced group reveal with minimal drift.',
      staggerMs: 80,
    ),
    SceneMotionRecipeDefinition(
      id: 'gridStaggerProfessional',
      category: SceneMotionRecipeCategory.group,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 0.86,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.9,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'enter',
          property: 'opacity',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 0.8,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'group', 'cardShell'},
      tasteNotes: 'Professional stagger for multi-card grid scenes.',
      staggerMs: 90,
    ),
    // Transition
    SceneMotionRecipeDefinition(
      id: 'morphIconToPromptBar',
      category: SceneMotionRecipeCategory.transition,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.0,
          toValue: 3.6,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'shape',
          property: 'width',
          fromValue: 112.0,
          toValue: 860.0,
          startFraction: 0.08,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'cardShell'},
      tasteNotes: 'Connected morph from app icon into prompt container.',
    ),
    SceneMotionRecipeDefinition(
      id: 'promptBarToFullscreenCircle',
      category: SceneMotionRecipeCategory.transition,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'cover',
          property: 'scale',
          fromValue: 1.0,
          toValue: 18.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'button', 'component'},
      tasteNotes: 'Press-to-cover transition used in prompt scenes.',
    ),
    SceneMotionRecipeDefinition(
      id: 'matchCutSlide',
      category: SceneMotionRecipeCategory.transition,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'slide',
          property: 'position',
          fromValue: <String, double>{'x': 0, 'y': 0},
          toValue: <String, double>{'x': -240, 'y': 0},
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.fast',
      easingToken: r'$easing.snappy',
      speedyGraphPreset: 'fastSlow',
      allowedTargets: <String>{'group', 'component'},
      tasteNotes: 'Match-cut directional handoff.',
    ),
    SceneMotionRecipeDefinition(
      id: 'scaleThrough',
      category: SceneMotionRecipeCategory.transition,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.0,
          toValue: 1.55,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'group', 'component', 'backgroundElement'},
      tasteNotes: 'Scale-through transition for scene depth.',
    ),
    SceneMotionRecipeDefinition(
      id: 'wipeByShape',
      category: SceneMotionRecipeCategory.transition,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'wipe',
          property: 'reveal',
          fromValue: 0.0,
          toValue: 1.0,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.standard',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'component', 'group', 'backgroundElement'},
      tasteNotes: 'Shape wipe transition with deterministic edge.',
    ),
    SceneMotionRecipeDefinition(
      id: 'pushDepth',
      category: SceneMotionRecipeCategory.transition,
      channels: <SceneMotionRecipeChannel>[
        SceneMotionRecipeChannel(
          kind: 'scale',
          property: 'scale',
          fromValue: 1.0,
          toValue: 0.78,
          startFraction: 0.0,
          endFraction: 1.0,
          easing: 'slowFastSlow',
        ),
        SceneMotionRecipeChannel(
          kind: 'fade',
          property: 'opacity',
          fromValue: 1.0,
          toValue: 0.0,
          startFraction: 0.3,
          endFraction: 1.0,
          easing: 'fastSlow',
        ),
      ],
      defaultDurationToken: r'$duration.medium',
      easingToken: r'$easing.expressive',
      speedyGraphPreset: 'slowFastSlow',
      allowedTargets: <String>{'group', 'component'},
      tasteNotes: 'Depth push transition with clean hold release.',
    ),
  ];

  static final Map<String, SceneMotionRecipeDefinition> _byToken =
      <String, SceneMotionRecipeDefinition>{
    for (final definition in _definitions)
      _normalize(definition.id): definition,
    for (final definition in _definitions)
      _normalize('\$motion.${definition.id}'): definition,
  };

  List<SceneMotionRecipeDefinition> get all => _definitions;

  SceneMotionRecipeDefinition? find(String recipeId) {
    return _byToken[_normalize(recipeId)];
  }

  static String _normalize(String value) {
    return value.trim().toLowerCase().replaceAll(RegExp(r'[^a-z0-9]+'), '');
  }
}
